### ISSUE TITLE
Issue: Menu opens, but can't scroll, etc. Pressing up dpad closes the menu. Controls are frozen during this.

### ISSUE THREAD

**Issue by MistressPlague** [shiversoftdev/Iconic-Evanescence#1]
Any ideas?

Context:
Compiler: GSC Studio

Changes:
Removed big what I presume is comments in main.gsc, from line 8 so it compiles, in-game everything seems fine except the control system, where opening the menu works fine, but after no controls work except the open binding somehow triggering the else if right after open; reading Buttons[5]: `else if( self IsButtonPressed( Buttons[5] ) && Menu.currentmenu == MAIN )`

Adding iprintln logs is how I know that is the statement triggering, I presume it is not cause, but result of the actual issue.

**Comment by shiversoftdev** [comment]
You need the theme inject as well - https://www.youtube.com/watch?v=_x9ePPQNuZg.

**Comment by MistressPlague** [comment]
Thanks!
On testing, it works but seems to crash my console on origins?
My origins runs fine, tested without menu to be sure.

**Comment by shiversoftdev** [comment]
Use GSX studio to compile this project.

**Comment by MistressPlague** [comment]
Works now, but weirdly, my _shellshock preference for bg alpha is ignored, but wasn't before with gsc studio. It's 204.
All of my other preferences in _shellshock seem to work however.

Any ideas?

EDIT: Presuming I can't compile _shellshock in GSX Studio for some reason?

**Comment by shiversoftdev** [comment]
you can compile and inject both at the same time with gsx studio. add a script on the left and set the path correctly.

**Comment by MistressPlague** [comment]
Then do you have any ideas about my bg alpha issue?
